language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.5"
dist: trusty

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility
      - "python-lxml"
      - "python-simplejson"
      - "python-serial"
      - "python-yaml"
      - "python-cairo"
      - "cups"
      - "libcups2-dev"

stages:
  - test

jobs:
  include:
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT="1"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="OCA/OCB"
env:
  global:
    - VERSION="11.0" TESTS="0" LINT_CHECK="0" MAKEPOT="1"
    - WKHTMLTOPDF_VERSION="0.12.5"

install:
  - git clone --depth=1
    https://github.com/simetri-sinergi-id/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - git clone -b 11.0 https://github.com/aeroo/aeroo_reports.git ${HOME}/aeroo_reports
  - pip install unidecode==1.2.0
  - pip install pycups==1.9.73
  - pip install git+https://github.com/adhoc-dev/aeroolib@master-fix-ods
  - pip install git+https://github.com/edgewall/genshi@stable/0.7.x
  - pip install git+https://github.com/aeroo/currency2text.git
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
